// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: ChatMsg.proto

package protodef

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMsgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMsgRequest) Reset() {
	*x = ChatMsgRequest{}
	mi := &file_ChatMsg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsgRequest) ProtoMessage() {}

func (x *ChatMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ChatMsg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsgRequest.ProtoReflect.Descriptor instead.
func (*ChatMsgRequest) Descriptor() ([]byte, []int) {
	return file_ChatMsg_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMsgRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatMsgNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *Player                `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMsgNotification) Reset() {
	*x = ChatMsgNotification{}
	mi := &file_ChatMsg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMsgNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsgNotification) ProtoMessage() {}

func (x *ChatMsgNotification) ProtoReflect() protoreflect.Message {
	mi := &file_ChatMsg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsgNotification.ProtoReflect.Descriptor instead.
func (*ChatMsgNotification) Descriptor() ([]byte, []int) {
	return file_ChatMsg_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMsgNotification) GetFrom() *Player {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ChatMsgNotification) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_ChatMsg_proto protoreflect.FileDescriptor

const file_ChatMsg_proto_rawDesc = "" +
	"\n" +
	"\rChatMsg.proto\x12\bDouDizhu\x1a\fPlayer.proto\"*\n" +
	"\x0eChatMsgRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"U\n" +
	"\x13ChatMsgNotification\x12$\n" +
	"\x04from\x18\x01 \x01(\v2\x10.DouDizhu.PlayerR\x04from\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontentB\"Z\x10network/protodef\xaa\x02\rNetwork.Protob\x06proto3"

var (
	file_ChatMsg_proto_rawDescOnce sync.Once
	file_ChatMsg_proto_rawDescData []byte
)

func file_ChatMsg_proto_rawDescGZIP() []byte {
	file_ChatMsg_proto_rawDescOnce.Do(func() {
		file_ChatMsg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ChatMsg_proto_rawDesc), len(file_ChatMsg_proto_rawDesc)))
	})
	return file_ChatMsg_proto_rawDescData
}

var file_ChatMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ChatMsg_proto_goTypes = []any{
	(*ChatMsgRequest)(nil),      // 0: DouDizhu.ChatMsgRequest
	(*ChatMsgNotification)(nil), // 1: DouDizhu.ChatMsgNotification
	(*Player)(nil),              // 2: DouDizhu.Player
}
var file_ChatMsg_proto_depIdxs = []int32{
	2, // 0: DouDizhu.ChatMsgNotification.from:type_name -> DouDizhu.Player
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ChatMsg_proto_init() }
func file_ChatMsg_proto_init() {
	if File_ChatMsg_proto != nil {
		return
	}
	file_Player_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ChatMsg_proto_rawDesc), len(file_ChatMsg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ChatMsg_proto_goTypes,
		DependencyIndexes: file_ChatMsg_proto_depIdxs,
		MessageInfos:      file_ChatMsg_proto_msgTypes,
	}.Build()
	File_ChatMsg_proto = out.File
	file_ChatMsg_proto_goTypes = nil
	file_ChatMsg_proto_depIdxs = nil
}
