// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: GameMsg.proto

package protodef

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PGameMsgHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用于标识请求的唯一id
	MessageId     int64    `protobuf:"varint,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	Player        *PPlayer `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PGameMsgHeader) Reset() {
	*x = PGameMsgHeader{}
	mi := &file_GameMsg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGameMsgHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGameMsgHeader) ProtoMessage() {}

func (x *PGameMsgHeader) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGameMsgHeader.ProtoReflect.Descriptor instead.
func (*PGameMsgHeader) Descriptor() ([]byte, []int) {
	return file_GameMsg_proto_rawDescGZIP(), []int{0}
}

func (x *PGameMsgHeader) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *PGameMsgHeader) GetPlayer() *PPlayer {
	if x != nil {
		return x.Player
	}
	return nil
}

type PGameClientMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *PGameMsgHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*PGameClientMessage_ChatMsg
	Content       isPGameClientMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PGameClientMessage) Reset() {
	*x = PGameClientMessage{}
	mi := &file_GameMsg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGameClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGameClientMessage) ProtoMessage() {}

func (x *PGameClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGameClientMessage.ProtoReflect.Descriptor instead.
func (*PGameClientMessage) Descriptor() ([]byte, []int) {
	return file_GameMsg_proto_rawDescGZIP(), []int{1}
}

func (x *PGameClientMessage) GetHeader() *PGameMsgHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PGameClientMessage) GetContent() isPGameClientMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PGameClientMessage) GetChatMsg() *PChatMsgRequest {
	if x != nil {
		if x, ok := x.Content.(*PGameClientMessage_ChatMsg); ok {
			return x.ChatMsg
		}
	}
	return nil
}

type isPGameClientMessage_Content interface {
	isPGameClientMessage_Content()
}

type PGameClientMessage_ChatMsg struct {
	ChatMsg *PChatMsgRequest `protobuf:"bytes,2,opt,name=chatMsg,proto3,oneof"`
}

func (*PGameClientMessage_ChatMsg) isPGameClientMessage_Content() {}

type PGameServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*PGameServerMessage_Response
	//	*PGameServerMessage_Notification
	Content       isPGameServerMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PGameServerMessage) Reset() {
	*x = PGameServerMessage{}
	mi := &file_GameMsg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGameServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGameServerMessage) ProtoMessage() {}

func (x *PGameServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGameServerMessage.ProtoReflect.Descriptor instead.
func (*PGameServerMessage) Descriptor() ([]byte, []int) {
	return file_GameMsg_proto_rawDescGZIP(), []int{2}
}

func (x *PGameServerMessage) GetContent() isPGameServerMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PGameServerMessage) GetResponse() *PGameMsgRespPacket {
	if x != nil {
		if x, ok := x.Content.(*PGameServerMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *PGameServerMessage) GetNotification() *PGameNotificationPacket {
	if x != nil {
		if x, ok := x.Content.(*PGameServerMessage_Notification); ok {
			return x.Notification
		}
	}
	return nil
}

type isPGameServerMessage_Content interface {
	isPGameServerMessage_Content()
}

type PGameServerMessage_Response struct {
	Response *PGameMsgRespPacket `protobuf:"bytes,1,opt,name=response,proto3,oneof"`
}

type PGameServerMessage_Notification struct {
	Notification *PGameNotificationPacket `protobuf:"bytes,2,opt,name=notification,proto3,oneof"`
}

func (*PGameServerMessage_Response) isPGameServerMessage_Content() {}

func (*PGameServerMessage_Notification) isPGameServerMessage_Content() {}

type PGameMsgRespPacket struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *PGameMsgHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*PGameMsgRespPacket_Error
	//	*PGameMsgRespPacket_CommonResponse
	Content       isPGameMsgRespPacket_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PGameMsgRespPacket) Reset() {
	*x = PGameMsgRespPacket{}
	mi := &file_GameMsg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGameMsgRespPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGameMsgRespPacket) ProtoMessage() {}

func (x *PGameMsgRespPacket) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGameMsgRespPacket.ProtoReflect.Descriptor instead.
func (*PGameMsgRespPacket) Descriptor() ([]byte, []int) {
	return file_GameMsg_proto_rawDescGZIP(), []int{3}
}

func (x *PGameMsgRespPacket) GetHeader() *PGameMsgHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PGameMsgRespPacket) GetContent() isPGameMsgRespPacket_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PGameMsgRespPacket) GetError() *PError {
	if x != nil {
		if x, ok := x.Content.(*PGameMsgRespPacket_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *PGameMsgRespPacket) GetCommonResponse() *PCommonResponse {
	if x != nil {
		if x, ok := x.Content.(*PGameMsgRespPacket_CommonResponse); ok {
			return x.CommonResponse
		}
	}
	return nil
}

type isPGameMsgRespPacket_Content interface {
	isPGameMsgRespPacket_Content()
}

type PGameMsgRespPacket_Error struct {
	Error *PError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type PGameMsgRespPacket_CommonResponse struct {
	CommonResponse *PCommonResponse `protobuf:"bytes,3,opt,name=commonResponse,proto3,oneof"`
}

func (*PGameMsgRespPacket_Error) isPGameMsgRespPacket_Content() {}

func (*PGameMsgRespPacket_CommonResponse) isPGameMsgRespPacket_Content() {}

type PGameNotificationPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*PGameNotificationPacket_ChatMsg
	Content       isPGameNotificationPacket_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PGameNotificationPacket) Reset() {
	*x = PGameNotificationPacket{}
	mi := &file_GameMsg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGameNotificationPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGameNotificationPacket) ProtoMessage() {}

func (x *PGameNotificationPacket) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGameNotificationPacket.ProtoReflect.Descriptor instead.
func (*PGameNotificationPacket) Descriptor() ([]byte, []int) {
	return file_GameMsg_proto_rawDescGZIP(), []int{4}
}

func (x *PGameNotificationPacket) GetContent() isPGameNotificationPacket_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PGameNotificationPacket) GetChatMsg() *PChatMsgNotification {
	if x != nil {
		if x, ok := x.Content.(*PGameNotificationPacket_ChatMsg); ok {
			return x.ChatMsg
		}
	}
	return nil
}

type isPGameNotificationPacket_Content interface {
	isPGameNotificationPacket_Content()
}

type PGameNotificationPacket_ChatMsg struct {
	ChatMsg *PChatMsgNotification `protobuf:"bytes,1,opt,name=chatMsg,proto3,oneof"`
}

func (*PGameNotificationPacket_ChatMsg) isPGameNotificationPacket_Content() {}

// 不需要返回值可用这个
type PCommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PCommonResponse) Reset() {
	*x = PCommonResponse{}
	mi := &file_GameMsg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCommonResponse) ProtoMessage() {}

func (x *PCommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCommonResponse.ProtoReflect.Descriptor instead.
func (*PCommonResponse) Descriptor() ([]byte, []int) {
	return file_GameMsg_proto_rawDescGZIP(), []int{5}
}

var File_GameMsg_proto protoreflect.FileDescriptor

const file_GameMsg_proto_rawDesc = "" +
	"\n" +
	"\rGameMsg.proto\x12\bDouDizhu\x1a\vError.proto\x1a\rChatMsg.proto\x1a\fPlayer.proto\"Y\n" +
	"\x0ePGameMsgHeader\x12\x1c\n" +
	"\tmessageId\x18\x01 \x01(\x03R\tmessageId\x12)\n" +
	"\x06player\x18\x02 \x01(\v2\x11.DouDizhu.PPlayerR\x06player\"\x88\x01\n" +
	"\x12PGameClientMessage\x120\n" +
	"\x06header\x18\x01 \x01(\v2\x18.DouDizhu.PGameMsgHeaderR\x06header\x125\n" +
	"\achatMsg\x18\x02 \x01(\v2\x19.DouDizhu.PChatMsgRequestH\x00R\achatMsgB\t\n" +
	"\acontent\"\xa4\x01\n" +
	"\x12PGameServerMessage\x12:\n" +
	"\bresponse\x18\x01 \x01(\v2\x1c.DouDizhu.PGameMsgRespPacketH\x00R\bresponse\x12G\n" +
	"\fnotification\x18\x02 \x01(\v2!.DouDizhu.PGameNotificationPacketH\x00R\fnotificationB\t\n" +
	"\acontent\"\xc0\x01\n" +
	"\x12PGameMsgRespPacket\x120\n" +
	"\x06header\x18\x01 \x01(\v2\x18.DouDizhu.PGameMsgHeaderR\x06header\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\x10.DouDizhu.PErrorH\x00R\x05error\x12C\n" +
	"\x0ecommonResponse\x18\x03 \x01(\v2\x19.DouDizhu.PCommonResponseH\x00R\x0ecommonResponseB\t\n" +
	"\acontent\"`\n" +
	"\x17PGameNotificationPacket\x12:\n" +
	"\achatMsg\x18\x01 \x01(\v2\x1e.DouDizhu.PChatMsgNotificationH\x00R\achatMsgB\t\n" +
	"\acontent\"\x11\n" +
	"\x0fPCommonResponseB\"Z\x10network/protodef\xaa\x02\rNetwork.Protob\x06proto3"

var (
	file_GameMsg_proto_rawDescOnce sync.Once
	file_GameMsg_proto_rawDescData []byte
)

func file_GameMsg_proto_rawDescGZIP() []byte {
	file_GameMsg_proto_rawDescOnce.Do(func() {
		file_GameMsg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GameMsg_proto_rawDesc), len(file_GameMsg_proto_rawDesc)))
	})
	return file_GameMsg_proto_rawDescData
}

var file_GameMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_GameMsg_proto_goTypes = []any{
	(*PGameMsgHeader)(nil),          // 0: DouDizhu.PGameMsgHeader
	(*PGameClientMessage)(nil),      // 1: DouDizhu.PGameClientMessage
	(*PGameServerMessage)(nil),      // 2: DouDizhu.PGameServerMessage
	(*PGameMsgRespPacket)(nil),      // 3: DouDizhu.PGameMsgRespPacket
	(*PGameNotificationPacket)(nil), // 4: DouDizhu.PGameNotificationPacket
	(*PCommonResponse)(nil),         // 5: DouDizhu.PCommonResponse
	(*PPlayer)(nil),                 // 6: DouDizhu.PPlayer
	(*PChatMsgRequest)(nil),         // 7: DouDizhu.PChatMsgRequest
	(*PError)(nil),                  // 8: DouDizhu.PError
	(*PChatMsgNotification)(nil),    // 9: DouDizhu.PChatMsgNotification
}
var file_GameMsg_proto_depIdxs = []int32{
	6, // 0: DouDizhu.PGameMsgHeader.player:type_name -> DouDizhu.PPlayer
	0, // 1: DouDizhu.PGameClientMessage.header:type_name -> DouDizhu.PGameMsgHeader
	7, // 2: DouDizhu.PGameClientMessage.chatMsg:type_name -> DouDizhu.PChatMsgRequest
	3, // 3: DouDizhu.PGameServerMessage.response:type_name -> DouDizhu.PGameMsgRespPacket
	4, // 4: DouDizhu.PGameServerMessage.notification:type_name -> DouDizhu.PGameNotificationPacket
	0, // 5: DouDizhu.PGameMsgRespPacket.header:type_name -> DouDizhu.PGameMsgHeader
	8, // 6: DouDizhu.PGameMsgRespPacket.error:type_name -> DouDizhu.PError
	5, // 7: DouDizhu.PGameMsgRespPacket.commonResponse:type_name -> DouDizhu.PCommonResponse
	9, // 8: DouDizhu.PGameNotificationPacket.chatMsg:type_name -> DouDizhu.PChatMsgNotification
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_GameMsg_proto_init() }
func file_GameMsg_proto_init() {
	if File_GameMsg_proto != nil {
		return
	}
	file_Error_proto_init()
	file_ChatMsg_proto_init()
	file_Player_proto_init()
	file_GameMsg_proto_msgTypes[1].OneofWrappers = []any{
		(*PGameClientMessage_ChatMsg)(nil),
	}
	file_GameMsg_proto_msgTypes[2].OneofWrappers = []any{
		(*PGameServerMessage_Response)(nil),
		(*PGameServerMessage_Notification)(nil),
	}
	file_GameMsg_proto_msgTypes[3].OneofWrappers = []any{
		(*PGameMsgRespPacket_Error)(nil),
		(*PGameMsgRespPacket_CommonResponse)(nil),
	}
	file_GameMsg_proto_msgTypes[4].OneofWrappers = []any{
		(*PGameNotificationPacket_ChatMsg)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GameMsg_proto_rawDesc), len(file_GameMsg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GameMsg_proto_goTypes,
		DependencyIndexes: file_GameMsg_proto_depIdxs,
		MessageInfos:      file_GameMsg_proto_msgTypes,
	}.Build()
	File_GameMsg_proto = out.File
	file_GameMsg_proto_goTypes = nil
	file_GameMsg_proto_depIdxs = nil
}
