// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: Login.proto

package protodef

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PRegisterRequest) Reset() {
	*x = PRegisterRequest{}
	mi := &file_Login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRegisterRequest) ProtoMessage() {}

func (x *PRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRegisterRequest.ProtoReflect.Descriptor instead.
func (*PRegisterRequest) Descriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{0}
}

func (x *PRegisterRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PRegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PLoginRequest) Reset() {
	*x = PLoginRequest{}
	mi := &file_Login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PLoginRequest) ProtoMessage() {}

func (x *PLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PLoginRequest.ProtoReflect.Descriptor instead.
func (*PLoginRequest) Descriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{1}
}

func (x *PLoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PLoginResponse) Reset() {
	*x = PLoginResponse{}
	mi := &file_Login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PLoginResponse) ProtoMessage() {}

func (x *PLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PLoginResponse.ProtoReflect.Descriptor instead.
func (*PLoginResponse) Descriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{2}
}

func (x *PLoginResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

var File_Login_proto protoreflect.FileDescriptor

const file_Login_proto_rawDesc = "" +
	"\n" +
	"\vLogin.proto\x12\bDouDizhu\"H\n" +
	"\x10PRegisterRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"E\n" +
	"\rPLoginRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\",\n" +
	"\x0ePLoginResponse\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerIdB\"Z\x10network/protodef\xaa\x02\rNetwork.Protob\x06proto3"

var (
	file_Login_proto_rawDescOnce sync.Once
	file_Login_proto_rawDescData []byte
)

func file_Login_proto_rawDescGZIP() []byte {
	file_Login_proto_rawDescOnce.Do(func() {
		file_Login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Login_proto_rawDesc), len(file_Login_proto_rawDesc)))
	})
	return file_Login_proto_rawDescData
}

var file_Login_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Login_proto_goTypes = []any{
	(*PRegisterRequest)(nil), // 0: DouDizhu.PRegisterRequest
	(*PLoginRequest)(nil),    // 1: DouDizhu.PLoginRequest
	(*PLoginResponse)(nil),   // 2: DouDizhu.PLoginResponse
}
var file_Login_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Login_proto_init() }
func file_Login_proto_init() {
	if File_Login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Login_proto_rawDesc), len(file_Login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Login_proto_goTypes,
		DependencyIndexes: file_Login_proto_depIdxs,
		MessageInfos:      file_Login_proto_msgTypes,
	}.Build()
	File_Login_proto = out.File
	file_Login_proto_goTypes = nil
	file_Login_proto_depIdxs = nil
}
