// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: Login.proto

package protodef

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PRegistResponse_Result int32

const (
	PRegistResponse_RESULT_UNKNOWN                 PRegistResponse_Result = 0
	PRegistResponse_RESULT_SUCCESS                 PRegistResponse_Result = 1
	PRegistResponse_RESULT_ACCOUNT_EXISTS          PRegistResponse_Result = 2
	PRegistResponse_RESULT_ACCOUNT_TOO_LONG        PRegistResponse_Result = 3
	PRegistResponse_RESULT_ACCOUNT_TOO_SHORT       PRegistResponse_Result = 4
	PRegistResponse_RESULT_ACCOUNT_FORMAT_INVALID  PRegistResponse_Result = 5
	PRegistResponse_RESULT_PASSWORD_TOO_LONG       PRegistResponse_Result = 6
	PRegistResponse_RESULT_PASSWORD_TOO_SHORT      PRegistResponse_Result = 7
	PRegistResponse_RESULT_PASSWORD_FORMAT_INVALID PRegistResponse_Result = 8
)

// Enum value maps for PRegistResponse_Result.
var (
	PRegistResponse_Result_name = map[int32]string{
		0: "RESULT_UNKNOWN",
		1: "RESULT_SUCCESS",
		2: "RESULT_ACCOUNT_EXISTS",
		3: "RESULT_ACCOUNT_TOO_LONG",
		4: "RESULT_ACCOUNT_TOO_SHORT",
		5: "RESULT_ACCOUNT_FORMAT_INVALID",
		6: "RESULT_PASSWORD_TOO_LONG",
		7: "RESULT_PASSWORD_TOO_SHORT",
		8: "RESULT_PASSWORD_FORMAT_INVALID",
	}
	PRegistResponse_Result_value = map[string]int32{
		"RESULT_UNKNOWN":                 0,
		"RESULT_SUCCESS":                 1,
		"RESULT_ACCOUNT_EXISTS":          2,
		"RESULT_ACCOUNT_TOO_LONG":        3,
		"RESULT_ACCOUNT_TOO_SHORT":       4,
		"RESULT_ACCOUNT_FORMAT_INVALID":  5,
		"RESULT_PASSWORD_TOO_LONG":       6,
		"RESULT_PASSWORD_TOO_SHORT":      7,
		"RESULT_PASSWORD_FORMAT_INVALID": 8,
	}
)

func (x PRegistResponse_Result) Enum() *PRegistResponse_Result {
	p := new(PRegistResponse_Result)
	*p = x
	return p
}

func (x PRegistResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PRegistResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_Login_proto_enumTypes[0].Descriptor()
}

func (PRegistResponse_Result) Type() protoreflect.EnumType {
	return &file_Login_proto_enumTypes[0]
}

func (x PRegistResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PRegistResponse_Result.Descriptor instead.
func (PRegistResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{1, 0}
}

type PLoginResponse_Result int32

const (
	PLoginResponse_RESULT_UNKNOWN            PLoginResponse_Result = 0
	PLoginResponse_RESULT_SUCCESS            PLoginResponse_Result = 1
	PLoginResponse_RESULT_ACCOUNT_NOT_EXISTS PLoginResponse_Result = 2
	PLoginResponse_RESULT_PASSWORD_WRONG     PLoginResponse_Result = 3
)

// Enum value maps for PLoginResponse_Result.
var (
	PLoginResponse_Result_name = map[int32]string{
		0: "RESULT_UNKNOWN",
		1: "RESULT_SUCCESS",
		2: "RESULT_ACCOUNT_NOT_EXISTS",
		3: "RESULT_PASSWORD_WRONG",
	}
	PLoginResponse_Result_value = map[string]int32{
		"RESULT_UNKNOWN":            0,
		"RESULT_SUCCESS":            1,
		"RESULT_ACCOUNT_NOT_EXISTS": 2,
		"RESULT_PASSWORD_WRONG":     3,
	}
)

func (x PLoginResponse_Result) Enum() *PLoginResponse_Result {
	p := new(PLoginResponse_Result)
	*p = x
	return p
}

func (x PLoginResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PLoginResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_Login_proto_enumTypes[1].Descriptor()
}

func (PLoginResponse_Result) Type() protoreflect.EnumType {
	return &file_Login_proto_enumTypes[1]
}

func (x PLoginResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PLoginResponse_Result.Descriptor instead.
func (PLoginResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{3, 0}
}

type PRegistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PRegistRequest) Reset() {
	*x = PRegistRequest{}
	mi := &file_Login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PRegistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRegistRequest) ProtoMessage() {}

func (x *PRegistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRegistRequest.ProtoReflect.Descriptor instead.
func (*PRegistRequest) Descriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{0}
}

func (x *PRegistRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PRegistRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PRegistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        PRegistResponse_Result `protobuf:"varint,1,opt,name=result,proto3,enum=DouDizhu.PRegistResponse_Result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PRegistResponse) Reset() {
	*x = PRegistResponse{}
	mi := &file_Login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PRegistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PRegistResponse) ProtoMessage() {}

func (x *PRegistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PRegistResponse.ProtoReflect.Descriptor instead.
func (*PRegistResponse) Descriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{1}
}

func (x *PRegistResponse) GetResult() PRegistResponse_Result {
	if x != nil {
		return x.Result
	}
	return PRegistResponse_RESULT_UNKNOWN
}

type PLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PLoginRequest) Reset() {
	*x = PLoginRequest{}
	mi := &file_Login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PLoginRequest) ProtoMessage() {}

func (x *PLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PLoginRequest.ProtoReflect.Descriptor instead.
func (*PLoginRequest) Descriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{2}
}

func (x *PLoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        PLoginResponse_Result  `protobuf:"varint,1,opt,name=result,proto3,enum=DouDizhu.PLoginResponse_Result" json:"result,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PLoginResponse) Reset() {
	*x = PLoginResponse{}
	mi := &file_Login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PLoginResponse) ProtoMessage() {}

func (x *PLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PLoginResponse.ProtoReflect.Descriptor instead.
func (*PLoginResponse) Descriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{3}
}

func (x *PLoginResponse) GetResult() PLoginResponse_Result {
	if x != nil {
		return x.Result
	}
	return PLoginResponse_RESULT_UNKNOWN
}

func (x *PLoginResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

var File_Login_proto protoreflect.FileDescriptor

const file_Login_proto_rawDesc = "" +
	"\n" +
	"\vLogin.proto\x12\bDouDizhu\"F\n" +
	"\x0ePRegistRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xd8\x02\n" +
	"\x0fPRegistResponse\x128\n" +
	"\x06result\x18\x01 \x01(\x0e2 .DouDizhu.PRegistResponse.ResultR\x06result\"\x8a\x02\n" +
	"\x06Result\x12\x12\n" +
	"\x0eRESULT_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eRESULT_SUCCESS\x10\x01\x12\x19\n" +
	"\x15RESULT_ACCOUNT_EXISTS\x10\x02\x12\x1b\n" +
	"\x17RESULT_ACCOUNT_TOO_LONG\x10\x03\x12\x1c\n" +
	"\x18RESULT_ACCOUNT_TOO_SHORT\x10\x04\x12!\n" +
	"\x1dRESULT_ACCOUNT_FORMAT_INVALID\x10\x05\x12\x1c\n" +
	"\x18RESULT_PASSWORD_TOO_LONG\x10\x06\x12\x1d\n" +
	"\x19RESULT_PASSWORD_TOO_SHORT\x10\a\x12\"\n" +
	"\x1eRESULT_PASSWORD_FORMAT_INVALID\x10\b\"E\n" +
	"\rPLoginRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xd1\x01\n" +
	"\x0ePLoginResponse\x127\n" +
	"\x06result\x18\x01 \x01(\x0e2\x1f.DouDizhu.PLoginResponse.ResultR\x06result\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\tR\bplayerId\"j\n" +
	"\x06Result\x12\x12\n" +
	"\x0eRESULT_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eRESULT_SUCCESS\x10\x01\x12\x1d\n" +
	"\x19RESULT_ACCOUNT_NOT_EXISTS\x10\x02\x12\x19\n" +
	"\x15RESULT_PASSWORD_WRONG\x10\x03B\"Z\x10network/protodef\xaa\x02\rNetwork.Protob\x06proto3"

var (
	file_Login_proto_rawDescOnce sync.Once
	file_Login_proto_rawDescData []byte
)

func file_Login_proto_rawDescGZIP() []byte {
	file_Login_proto_rawDescOnce.Do(func() {
		file_Login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Login_proto_rawDesc), len(file_Login_proto_rawDesc)))
	})
	return file_Login_proto_rawDescData
}

var file_Login_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_Login_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Login_proto_goTypes = []any{
	(PRegistResponse_Result)(0), // 0: DouDizhu.PRegistResponse.Result
	(PLoginResponse_Result)(0),  // 1: DouDizhu.PLoginResponse.Result
	(*PRegistRequest)(nil),      // 2: DouDizhu.PRegistRequest
	(*PRegistResponse)(nil),     // 3: DouDizhu.PRegistResponse
	(*PLoginRequest)(nil),       // 4: DouDizhu.PLoginRequest
	(*PLoginResponse)(nil),      // 5: DouDizhu.PLoginResponse
}
var file_Login_proto_depIdxs = []int32{
	0, // 0: DouDizhu.PRegistResponse.result:type_name -> DouDizhu.PRegistResponse.Result
	1, // 1: DouDizhu.PLoginResponse.result:type_name -> DouDizhu.PLoginResponse.Result
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Login_proto_init() }
func file_Login_proto_init() {
	if File_Login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Login_proto_rawDesc), len(file_Login_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Login_proto_goTypes,
		DependencyIndexes: file_Login_proto_depIdxs,
		EnumInfos:         file_Login_proto_enumTypes,
		MessageInfos:      file_Login_proto_msgTypes,
	}.Build()
	File_Login_proto = out.File
	file_Login_proto_goTypes = nil
	file_Login_proto_depIdxs = nil
}
