// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: Message.proto

package protodef

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameMsgHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMsgHeader) Reset() {
	*x = GameMsgHeader{}
	mi := &file_Message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMsgHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMsgHeader) ProtoMessage() {}

func (x *GameMsgHeader) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMsgHeader.ProtoReflect.Descriptor instead.
func (*GameMsgHeader) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0}
}

type GameMsgReqPacket struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *GameMsgHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*GameMsgReqPacket_ChatMsg
	Content       isGameMsgReqPacket_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMsgReqPacket) Reset() {
	*x = GameMsgReqPacket{}
	mi := &file_Message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMsgReqPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMsgReqPacket) ProtoMessage() {}

func (x *GameMsgReqPacket) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMsgReqPacket.ProtoReflect.Descriptor instead.
func (*GameMsgReqPacket) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{1}
}

func (x *GameMsgReqPacket) GetHeader() *GameMsgHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GameMsgReqPacket) GetContent() isGameMsgReqPacket_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GameMsgReqPacket) GetChatMsg() *ChatMsgRequest {
	if x != nil {
		if x, ok := x.Content.(*GameMsgReqPacket_ChatMsg); ok {
			return x.ChatMsg
		}
	}
	return nil
}

type isGameMsgReqPacket_Content interface {
	isGameMsgReqPacket_Content()
}

type GameMsgReqPacket_ChatMsg struct {
	ChatMsg *ChatMsgRequest `protobuf:"bytes,2,opt,name=chatMsg,proto3,oneof"`
}

func (*GameMsgReqPacket_ChatMsg) isGameMsgReqPacket_Content() {}

type GameMsgRespPacket struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *GameMsgHeader         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*GameMsgRespPacket_Error
	//	*GameMsgRespPacket_ChatMsg
	Content       isGameMsgRespPacket_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMsgRespPacket) Reset() {
	*x = GameMsgRespPacket{}
	mi := &file_Message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMsgRespPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMsgRespPacket) ProtoMessage() {}

func (x *GameMsgRespPacket) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMsgRespPacket.ProtoReflect.Descriptor instead.
func (*GameMsgRespPacket) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{2}
}

func (x *GameMsgRespPacket) GetHeader() *GameMsgHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GameMsgRespPacket) GetContent() isGameMsgRespPacket_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GameMsgRespPacket) GetError() *Error {
	if x != nil {
		if x, ok := x.Content.(*GameMsgRespPacket_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *GameMsgRespPacket) GetChatMsg() *ChatMsgResponse {
	if x != nil {
		if x, ok := x.Content.(*GameMsgRespPacket_ChatMsg); ok {
			return x.ChatMsg
		}
	}
	return nil
}

type isGameMsgRespPacket_Content interface {
	isGameMsgRespPacket_Content()
}

type GameMsgRespPacket_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type GameMsgRespPacket_ChatMsg struct {
	ChatMsg *ChatMsgResponse `protobuf:"bytes,3,opt,name=chatMsg,proto3,oneof"`
}

func (*GameMsgRespPacket_Error) isGameMsgRespPacket_Content() {}

func (*GameMsgRespPacket_ChatMsg) isGameMsgRespPacket_Content() {}

type ChatMsgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMsgRequest) Reset() {
	*x = ChatMsgRequest{}
	mi := &file_Message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsgRequest) ProtoMessage() {}

func (x *ChatMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsgRequest.ProtoReflect.Descriptor instead.
func (*ChatMsgRequest) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMsgRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatMsgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMsgResponse) Reset() {
	*x = ChatMsgResponse{}
	mi := &file_Message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsgResponse) ProtoMessage() {}

func (x *ChatMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsgResponse.ProtoReflect.Descriptor instead.
func (*ChatMsgResponse) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{4}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_Message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_Message_proto protoreflect.FileDescriptor

const file_Message_proto_rawDesc = "" +
	"\n" +
	"\rMessage.proto\x12\bDouDizhu\"\x0f\n" +
	"\rGameMsgHeader\"\x84\x01\n" +
	"\x10GameMsgReqPacket\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.DouDizhu.GameMsgHeaderR\x06header\x124\n" +
	"\achatMsg\x18\x02 \x01(\v2\x18.DouDizhu.ChatMsgRequestH\x00R\achatMsgB\t\n" +
	"\acontent\"\xaf\x01\n" +
	"\x11GameMsgRespPacket\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.DouDizhu.GameMsgHeaderR\x06header\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.DouDizhu.ErrorH\x00R\x05error\x125\n" +
	"\achatMsg\x18\x03 \x01(\v2\x19.DouDizhu.ChatMsgResponseH\x00R\achatMsgB\t\n" +
	"\acontent\"*\n" +
	"\x0eChatMsgRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\x11\n" +
	"\x0fChatMsgResponse\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\"Z\x10network/protodef\xaa\x02\rNetwork.Protob\x06proto3"

var (
	file_Message_proto_rawDescOnce sync.Once
	file_Message_proto_rawDescData []byte
)

func file_Message_proto_rawDescGZIP() []byte {
	file_Message_proto_rawDescOnce.Do(func() {
		file_Message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Message_proto_rawDesc), len(file_Message_proto_rawDesc)))
	})
	return file_Message_proto_rawDescData
}

var file_Message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Message_proto_goTypes = []any{
	(*GameMsgHeader)(nil),     // 0: DouDizhu.GameMsgHeader
	(*GameMsgReqPacket)(nil),  // 1: DouDizhu.GameMsgReqPacket
	(*GameMsgRespPacket)(nil), // 2: DouDizhu.GameMsgRespPacket
	(*ChatMsgRequest)(nil),    // 3: DouDizhu.ChatMsgRequest
	(*ChatMsgResponse)(nil),   // 4: DouDizhu.ChatMsgResponse
	(*Error)(nil),             // 5: DouDizhu.Error
}
var file_Message_proto_depIdxs = []int32{
	0, // 0: DouDizhu.GameMsgReqPacket.header:type_name -> DouDizhu.GameMsgHeader
	3, // 1: DouDizhu.GameMsgReqPacket.chatMsg:type_name -> DouDizhu.ChatMsgRequest
	0, // 2: DouDizhu.GameMsgRespPacket.header:type_name -> DouDizhu.GameMsgHeader
	5, // 3: DouDizhu.GameMsgRespPacket.error:type_name -> DouDizhu.Error
	4, // 4: DouDizhu.GameMsgRespPacket.chatMsg:type_name -> DouDizhu.ChatMsgResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_Message_proto_init() }
func file_Message_proto_init() {
	if File_Message_proto != nil {
		return
	}
	file_Message_proto_msgTypes[1].OneofWrappers = []any{
		(*GameMsgReqPacket_ChatMsg)(nil),
	}
	file_Message_proto_msgTypes[2].OneofWrappers = []any{
		(*GameMsgRespPacket_Error)(nil),
		(*GameMsgRespPacket_ChatMsg)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Message_proto_rawDesc), len(file_Message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Message_proto_goTypes,
		DependencyIndexes: file_Message_proto_depIdxs,
		MessageInfos:      file_Message_proto_msgTypes,
	}.Build()
	File_Message_proto = out.File
	file_Message_proto_goTypes = nil
	file_Message_proto_depIdxs = nil
}
