// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: Player.proto

package protodef

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PPlayer) Reset() {
	*x = PPlayer{}
	mi := &file_Player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PPlayer) ProtoMessage() {}

func (x *PPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_Player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PPlayer.ProtoReflect.Descriptor instead.
func (*PPlayer) Descriptor() ([]byte, []int) {
	return file_Player_proto_rawDescGZIP(), []int{0}
}

func (x *PPlayer) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PPlayer) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

var File_Player_proto protoreflect.FileDescriptor

const file_Player_proto_rawDesc = "" +
	"\n" +
	"\fPlayer.proto\x12\bDouDizhu\"A\n" +
	"\aPPlayer\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnicknameB\"Z\x10network/protodef\xaa\x02\rNetwork.Protob\x06proto3"

var (
	file_Player_proto_rawDescOnce sync.Once
	file_Player_proto_rawDescData []byte
)

func file_Player_proto_rawDescGZIP() []byte {
	file_Player_proto_rawDescOnce.Do(func() {
		file_Player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Player_proto_rawDesc), len(file_Player_proto_rawDesc)))
	})
	return file_Player_proto_rawDescData
}

var file_Player_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Player_proto_goTypes = []any{
	(*PPlayer)(nil), // 0: DouDizhu.PPlayer
}
var file_Player_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Player_proto_init() }
func file_Player_proto_init() {
	if File_Player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Player_proto_rawDesc), len(file_Player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Player_proto_goTypes,
		DependencyIndexes: file_Player_proto_depIdxs,
		MessageInfos:      file_Player_proto_msgTypes,
	}.Build()
	File_Player_proto = out.File
	file_Player_proto_goTypes = nil
	file_Player_proto_depIdxs = nil
}
