// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: GameMsg.proto

package protodef

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PServerMsgType int32

const (
	PServerMsgType_PSERVER_MSG_TYPE_UNKNOWN      PServerMsgType = 0
	PServerMsgType_PSERVER_MSG_TYPE_RESPONSE     PServerMsgType = 1
	PServerMsgType_PSERVER_MSG_TYPE_NOTIFICATION PServerMsgType = 2
	PServerMsgType_PSERVER_MSG_TYPE_ERROR        PServerMsgType = 3
)

// Enum value maps for PServerMsgType.
var (
	PServerMsgType_name = map[int32]string{
		0: "PSERVER_MSG_TYPE_UNKNOWN",
		1: "PSERVER_MSG_TYPE_RESPONSE",
		2: "PSERVER_MSG_TYPE_NOTIFICATION",
		3: "PSERVER_MSG_TYPE_ERROR",
	}
	PServerMsgType_value = map[string]int32{
		"PSERVER_MSG_TYPE_UNKNOWN":      0,
		"PSERVER_MSG_TYPE_RESPONSE":     1,
		"PSERVER_MSG_TYPE_NOTIFICATION": 2,
		"PSERVER_MSG_TYPE_ERROR":        3,
	}
)

func (x PServerMsgType) Enum() *PServerMsgType {
	p := new(PServerMsgType)
	*p = x
	return p
}

func (x PServerMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PServerMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_GameMsg_proto_enumTypes[0].Descriptor()
}

func (PServerMsgType) Type() protoreflect.EnumType {
	return &file_GameMsg_proto_enumTypes[0]
}

func (x PServerMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PServerMsgType.Descriptor instead.
func (PServerMsgType) EnumDescriptor() ([]byte, []int) {
	return file_GameMsg_proto_rawDescGZIP(), []int{0}
}

type PMsgId int32

const (
	PMsgId_PMSG_ID_UNKNOWN   PMsgId = 0
	PMsgId_PMSG_ID_LOGIN     PMsgId = 1
	PMsgId_PMSG_ID_REGISTER  PMsgId = 2
	PMsgId_PMSG_ID_HANDSHAKE PMsgId = 3
	// 房间相关
	PMsgId_PMSG_ID_CREATE_ROOM    PMsgId = 10
	PMsgId_PMSG_ID_GET_ROOM_LIST  PMsgId = 11
	PMsgId_PMSG_ID_ENTER_ROOM     PMsgId = 12
	PMsgId_PMSG_ID_LEAVE_ROOM     PMsgId = 13
	PMsgId_PMSG_ID_ROOM_CHANGED   PMsgId = 14
	PMsgId_PMSG_ID_ROOM_DISBANDED PMsgId = 15
	// 聊天相关
	PMsgId_PMSG_ID_CHAT_MSG PMsgId = 30
	// 房间人物控制
	PMsgId_PMSG_ID_CHARACTER_MOVE  PMsgId = 60
	PMsgId_PMSG_ID_CHARACTER_STATE PMsgId = 61
	PMsgId_PMSG_ID_ENTER_WORLD     PMsgId = 62
	PMsgId_PMSG_ID_LEAVE_WORLD     PMsgId = 63
)

// Enum value maps for PMsgId.
var (
	PMsgId_name = map[int32]string{
		0:  "PMSG_ID_UNKNOWN",
		1:  "PMSG_ID_LOGIN",
		2:  "PMSG_ID_REGISTER",
		3:  "PMSG_ID_HANDSHAKE",
		10: "PMSG_ID_CREATE_ROOM",
		11: "PMSG_ID_GET_ROOM_LIST",
		12: "PMSG_ID_ENTER_ROOM",
		13: "PMSG_ID_LEAVE_ROOM",
		14: "PMSG_ID_ROOM_CHANGED",
		15: "PMSG_ID_ROOM_DISBANDED",
		30: "PMSG_ID_CHAT_MSG",
		60: "PMSG_ID_CHARACTER_MOVE",
		61: "PMSG_ID_CHARACTER_STATE",
		62: "PMSG_ID_ENTER_WORLD",
		63: "PMSG_ID_LEAVE_WORLD",
	}
	PMsgId_value = map[string]int32{
		"PMSG_ID_UNKNOWN":         0,
		"PMSG_ID_LOGIN":           1,
		"PMSG_ID_REGISTER":        2,
		"PMSG_ID_HANDSHAKE":       3,
		"PMSG_ID_CREATE_ROOM":     10,
		"PMSG_ID_GET_ROOM_LIST":   11,
		"PMSG_ID_ENTER_ROOM":      12,
		"PMSG_ID_LEAVE_ROOM":      13,
		"PMSG_ID_ROOM_CHANGED":    14,
		"PMSG_ID_ROOM_DISBANDED":  15,
		"PMSG_ID_CHAT_MSG":        30,
		"PMSG_ID_CHARACTER_MOVE":  60,
		"PMSG_ID_CHARACTER_STATE": 61,
		"PMSG_ID_ENTER_WORLD":     62,
		"PMSG_ID_LEAVE_WORLD":     63,
	}
)

func (x PMsgId) Enum() *PMsgId {
	p := new(PMsgId)
	*p = x
	return p
}

func (x PMsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PMsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_GameMsg_proto_enumTypes[1].Descriptor()
}

func (PMsgId) Type() protoreflect.EnumType {
	return &file_GameMsg_proto_enumTypes[1]
}

func (x PMsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PMsgId.Descriptor instead.
func (PMsgId) EnumDescriptor() ([]byte, []int) {
	return file_GameMsg_proto_rawDescGZIP(), []int{1}
}

type PMsgHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础字段
	UniqueId  int64  `protobuf:"varint,1,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MsgId     PMsgId `protobuf:"varint,3,opt,name=msgId,proto3,enum=DouDizhu.PMsgId" json:"msgId,omitempty"`
	// 会话字段
	SessionId string `protobuf:"bytes,10,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	PlayerId  string `protobuf:"bytes,11,opt,name=playerId,proto3" json:"playerId,omitempty"`
	// 安全字段
	Iv            []byte `protobuf:"bytes,20,opt,name=iv,proto3" json:"iv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PMsgHeader) Reset() {
	*x = PMsgHeader{}
	mi := &file_GameMsg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PMsgHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PMsgHeader) ProtoMessage() {}

func (x *PMsgHeader) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PMsgHeader.ProtoReflect.Descriptor instead.
func (*PMsgHeader) Descriptor() ([]byte, []int) {
	return file_GameMsg_proto_rawDescGZIP(), []int{0}
}

func (x *PMsgHeader) GetUniqueId() int64 {
	if x != nil {
		return x.UniqueId
	}
	return 0
}

func (x *PMsgHeader) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PMsgHeader) GetMsgId() PMsgId {
	if x != nil {
		return x.MsgId
	}
	return PMsgId_PMSG_ID_UNKNOWN
}

func (x *PMsgHeader) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PMsgHeader) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PMsgHeader) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

type PClientMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *PMsgHeader            `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PClientMsg) Reset() {
	*x = PClientMsg{}
	mi := &file_GameMsg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PClientMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PClientMsg) ProtoMessage() {}

func (x *PClientMsg) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PClientMsg.ProtoReflect.Descriptor instead.
func (*PClientMsg) Descriptor() ([]byte, []int) {
	return file_GameMsg_proto_rawDescGZIP(), []int{1}
}

func (x *PClientMsg) GetHeader() *PMsgHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PClientMsg) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PServerMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *PMsgHeader            `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	MsgType       PServerMsgType         `protobuf:"varint,2,opt,name=msgType,proto3,enum=DouDizhu.PServerMsgType" json:"msgType,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PServerMsg) Reset() {
	*x = PServerMsg{}
	mi := &file_GameMsg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PServerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PServerMsg) ProtoMessage() {}

func (x *PServerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PServerMsg.ProtoReflect.Descriptor instead.
func (*PServerMsg) Descriptor() ([]byte, []int) {
	return file_GameMsg_proto_rawDescGZIP(), []int{2}
}

func (x *PServerMsg) GetHeader() *PMsgHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PServerMsg) GetMsgType() PServerMsgType {
	if x != nil {
		return x.MsgType
	}
	return PServerMsgType_PSERVER_MSG_TYPE_UNKNOWN
}

func (x *PServerMsg) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PEmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PEmptyResponse) Reset() {
	*x = PEmptyResponse{}
	mi := &file_GameMsg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PEmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PEmptyResponse) ProtoMessage() {}

func (x *PEmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PEmptyResponse.ProtoReflect.Descriptor instead.
func (*PEmptyResponse) Descriptor() ([]byte, []int) {
	return file_GameMsg_proto_rawDescGZIP(), []int{3}
}

var File_GameMsg_proto protoreflect.FileDescriptor

const file_GameMsg_proto_rawDesc = "" +
	"\n" +
	"\rGameMsg.proto\x12\bDouDizhu\"\xb8\x01\n" +
	"\n" +
	"PMsgHeader\x12\x1a\n" +
	"\buniqueId\x18\x01 \x01(\x03R\buniqueId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12&\n" +
	"\x05msgId\x18\x03 \x01(\x0e2\x10.DouDizhu.PMsgIdR\x05msgId\x12\x1c\n" +
	"\tsessionId\x18\n" +
	" \x01(\tR\tsessionId\x12\x1a\n" +
	"\bplayerId\x18\v \x01(\tR\bplayerId\x12\x0e\n" +
	"\x02iv\x18\x14 \x01(\fR\x02iv\"T\n" +
	"\n" +
	"PClientMsg\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.DouDizhu.PMsgHeaderR\x06header\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x88\x01\n" +
	"\n" +
	"PServerMsg\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.DouDizhu.PMsgHeaderR\x06header\x122\n" +
	"\amsgType\x18\x02 \x01(\x0e2\x18.DouDizhu.PServerMsgTypeR\amsgType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x10\n" +
	"\x0ePEmptyResponse*\x8c\x01\n" +
	"\x0ePServerMsgType\x12\x1c\n" +
	"\x18PSERVER_MSG_TYPE_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19PSERVER_MSG_TYPE_RESPONSE\x10\x01\x12!\n" +
	"\x1dPSERVER_MSG_TYPE_NOTIFICATION\x10\x02\x12\x1a\n" +
	"\x16PSERVER_MSG_TYPE_ERROR\x10\x03*\xf8\x02\n" +
	"\x06PMsgId\x12\x13\n" +
	"\x0fPMSG_ID_UNKNOWN\x10\x00\x12\x11\n" +
	"\rPMSG_ID_LOGIN\x10\x01\x12\x14\n" +
	"\x10PMSG_ID_REGISTER\x10\x02\x12\x15\n" +
	"\x11PMSG_ID_HANDSHAKE\x10\x03\x12\x17\n" +
	"\x13PMSG_ID_CREATE_ROOM\x10\n" +
	"\x12\x19\n" +
	"\x15PMSG_ID_GET_ROOM_LIST\x10\v\x12\x16\n" +
	"\x12PMSG_ID_ENTER_ROOM\x10\f\x12\x16\n" +
	"\x12PMSG_ID_LEAVE_ROOM\x10\r\x12\x18\n" +
	"\x14PMSG_ID_ROOM_CHANGED\x10\x0e\x12\x1a\n" +
	"\x16PMSG_ID_ROOM_DISBANDED\x10\x0f\x12\x14\n" +
	"\x10PMSG_ID_CHAT_MSG\x10\x1e\x12\x1a\n" +
	"\x16PMSG_ID_CHARACTER_MOVE\x10<\x12\x1b\n" +
	"\x17PMSG_ID_CHARACTER_STATE\x10=\x12\x17\n" +
	"\x13PMSG_ID_ENTER_WORLD\x10>\x12\x17\n" +
	"\x13PMSG_ID_LEAVE_WORLD\x10?B\"Z\x10network/protodef\xaa\x02\rNetwork.Protob\x06proto3"

var (
	file_GameMsg_proto_rawDescOnce sync.Once
	file_GameMsg_proto_rawDescData []byte
)

func file_GameMsg_proto_rawDescGZIP() []byte {
	file_GameMsg_proto_rawDescOnce.Do(func() {
		file_GameMsg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_GameMsg_proto_rawDesc), len(file_GameMsg_proto_rawDesc)))
	})
	return file_GameMsg_proto_rawDescData
}

var file_GameMsg_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_GameMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_GameMsg_proto_goTypes = []any{
	(PServerMsgType)(0),    // 0: DouDizhu.PServerMsgType
	(PMsgId)(0),            // 1: DouDizhu.PMsgId
	(*PMsgHeader)(nil),     // 2: DouDizhu.PMsgHeader
	(*PClientMsg)(nil),     // 3: DouDizhu.PClientMsg
	(*PServerMsg)(nil),     // 4: DouDizhu.PServerMsg
	(*PEmptyResponse)(nil), // 5: DouDizhu.PEmptyResponse
}
var file_GameMsg_proto_depIdxs = []int32{
	1, // 0: DouDizhu.PMsgHeader.msgId:type_name -> DouDizhu.PMsgId
	2, // 1: DouDizhu.PClientMsg.header:type_name -> DouDizhu.PMsgHeader
	2, // 2: DouDizhu.PServerMsg.header:type_name -> DouDizhu.PMsgHeader
	0, // 3: DouDizhu.PServerMsg.msgType:type_name -> DouDizhu.PServerMsgType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_GameMsg_proto_init() }
func file_GameMsg_proto_init() {
	if File_GameMsg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_GameMsg_proto_rawDesc), len(file_GameMsg_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GameMsg_proto_goTypes,
		DependencyIndexes: file_GameMsg_proto_depIdxs,
		EnumInfos:         file_GameMsg_proto_enumTypes,
		MessageInfos:      file_GameMsg_proto_msgTypes,
	}.Build()
	File_GameMsg_proto = out.File
	file_GameMsg_proto_goTypes = nil
	file_GameMsg_proto_depIdxs = nil
}
